services:
  - type: web
    name: emiao-growth-script
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
